repos:
  - repo: https://github.com/psf/black-pre-commit-mirror # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks 
    rev: v4.6.0
    hooks:
    -   id: check-yaml # checks if yaml file is valid
    -   id: check-added-large-files # prevents adding large files, above 500kB
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: ["--in-place", "--black", "--style=sphinx"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: []
        exclude: package.lock.json
