name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.9", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up cache
      uses: actions/cache@v4.0.2
      with:
        path: .venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
    - name: Install dependencies
      run: |
        pip install .[dev]

    - name: Run style checks
      run: |
        make check-codestyle

    - name: Run tests
      run: |
        make test
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
