name: Safety Security Scan

on:
  push: # Run on every push to any branch
  pull_request: # Run on new pull requests

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: safety/safety@2.3.4
        with:
          api-key: ${{secrets.SAFETY_API_KEY}}